theme: minima
title: Neuroepidemiology Group
email: zhanyq8@mail.sysu.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
    Causal Inference, Survival Analysis, and Neuroepidemiology
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
  - jekyll-tex
minima:
  math: true
